export type Color = typeof color

export const color = [
  'accent-color',
  'background-color',
  'background',
  'border-block-end-color',
  'border-block-start-color',
  'border-bottom-color',
  'border-bottom',
  'border-color',
  'border-left-color',
  'border-left',
  'border-right-color',
  'border-right',
  'border-top-color',
  'border-top',
  'border',
  'box-shadow',
  'caret-color',
  'color',
  'column-rule-color',
  'fill',
  'filter',
  'opacity',
  'outline-color',
  'outline',
  'stroke',
  'text-decoration-color',
  'text-decoration',
  'text-shadow',
] as const
