export type Layout = typeof layout

export const layout = [
  // TODO: Investigate -epub- prefixed properties
  // https://developer.mozilla.org/en-US/docs/Web/CSS/caption-side
  '-epub-caption-side',
  '-ms-grid-column-align',
  '-ms-grid-column-span',
  '-ms-grid-column',
  '-ms-grid-columns',
  '-ms-grid-row-align',
  '-ms-grid-row-span',
  '-ms-grid-row',
  '-ms-grid-rows',
  '-webkit-grid-after',
  '-webkit-grid-auto-columns',
  '-webkit-grid-auto-flow',
  '-webkit-grid-auto-rows',
  '-webkit-grid-before',
  '-webkit-grid-column',
  '-webkit-grid-columns',
  '-webkit-grid-end',
  '-webkit-grid-row',
  '-webkit-grid-rows',
  '-webkit-grid-start',
  'align-content',
  'align-items',
  'align-self',
  'display',
  'flex-basis',
  'flex-direction',
  'flex-grow',
  'flex-shrink',
  'flex-wrap',
  'flex',
  'grid-area',
  'grid-auto-columns',
  'grid-auto-flow',
  'grid-auto-rows',
  'grid-column-end',
  'grid-column-gap',
  'grid-column-start',
  'grid-column',
  'grid-row-end',
  'grid-row-gap',
  'grid-row-start',
  'grid-row',
  'grid-template-areas',
  'grid-template-columns',
  'grid-template-rows',
  'grid-template',
  'grid',
  'height',
  'justify-content',
  'justify-self',
  'order',
  'position',
  'text-align',
  'transform',
  'width',
  'z-index',
] as const
