export type Spacing = typeof spacing

export const spacing = [
  'border-bottom-width',
  'border-bottom',
  'border-left-width',
  'border-left',
  'border-right-width',
  'border-right',
  'border-top-width',
  'border-top',
  'border-width',
  'border',
  'bottom',
  'column-gap',
  'gap',
  'grid-gap',
  'left',
  'margin-block-end',
  'margin-block-start',
  'margin-bottom',
  'margin-inline-end',
  'margin-inline-start',
  'margin-left',
  'margin-right',
  'margin-top',
  'margin',
  'max-height',
  'max-width',
  'min-height',
  'min-width',
  'padding-bottom',
  'padding-left',
  'padding-right',
  'padding-top',
  'padding',
  'right',
  'row-gap',
  'scale',
  'text-indent',
  'top',
] as const
