export type Typography = typeof typography

export const typography = [
  '-moz-font-feature-settings',
  '-moz-font-language-override',
  '-ms-font-feature-settings',
  '-webkit-font-feature-settings',
  '-webkit-font-kerning',
  '-webkit-font-size-delta',
  '-webkit-font-smoothing',
  '-webkit-font-variant-ligatures',
  'font-display',
  'font-family',
  'font-feature-settings',
  'font-kerning',
  'font-language-override',
  'font-optical-sizing',
  'font-palette',
  'font-size-adjust',
  'font-size',
  'font-stretch',
  'font-style',
  'font-synthesis-small-caps',
  'font-synthesis-style',
  'font-synthesis-weight',
  'font-synthesis',
  'font-variant-alternates',
  'font-variant-caps',
  'font-variant-east-asian',
  'font-variant-emoji',
  'font-variant-ligatures',
  'font-variant-numeric',
  'font-variant-position',
  'font-variant',
  'font-variation-settings',
  'font-weight',
  'font',
  'letter-spacing',
  'line-height',
  'text-decoration',
  'text-transform',
  'white-space',
  'word-break',
  'word-spacing',
  'word-wrap',
] as const
